### ISSUE TITLE
Upgrade to Gridstack 0.2.5

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter/dashboards#197]
I'm upgrading to a 0.2.5 pre-release version of Gridstack as part of PR #196. There are some changes coming in 0.2.5 that we need to handle:

> As of v0.2.5 all methods and parameters are in camel case to respect JavaScript Style Guide and Coding Conventions. All old methods and parameters are marked as deprecated and still available but a warning will be displayed in js console. They will be available until v1.0 when they will be completely removed.

Some other changes to consider (see 0.2.5 changelog):

> - add enableMove/enableResize methods.
> - add options disableDrag and disableResize

**Comment by dalogsdon** [comment]
FYI: Dashboards server updates Gridstack to 0.2.5 in https://github.com/jupyter-incubator/dashboards_server/pull/140 due to missing npm dependencies for 0.2.4.

**Comment by parente** [comment]
Merging with #18.
