### ISSUE TITLE
Newly added cells should be inserted in notebook order

### ISSUE THREAD

**Issue by dalogsdon** [jupyter/dashboards#207]
From https://github.com/jupyter-incubator/dashboards/pull/205#issuecomment-201970944:

> @parente: When I add a new cell that has output to a big notebook, it currently gets appended to the bottom of the layout. Should it instead appear in cell order as if I had clicked the middle + button option? I think this is closer to where I usually want the cell to appear than the end of the dashboard is.

**Comment by parente** [comment]
Nit. Won't fix.
