### ISSUE TITLE
Pandas dataframe in Dashboard

### ISSUE THREAD

**Issue by arita37** [jupyter/dashboards#283]
It seems that Pandas dataframe are not well rendered in Jupyter Dashboard.

Is there a way to show well defined table in Jupyter Dashboard ?

Thanks very much for your effort on this package.

**Comment by parente** [comment]
The dashboard preview and layout modes in this extension do not clip at the grid boundaries at the moment. Overflowing content is clipped, however, in the dashboard server project. We should probably make this consistent.
