### ISSUE TITLE
error on sudo npm install -g jupyter-dashboards-server

### ISSUE THREAD

**Issue by galenwilkerson** [jupyter/dashboards#287]
hi, I've had this issue on two different linux machines, when installing the server
thanks for any help.

Error log attached:
[npm-debug.log.TXT](https://github.com/jupyter/dashboards/files/731882/npm-debug.log.TXT)

Information and console:

> $ uname -a
> Linux VirtualBox 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> $ jupyter --version
> 4.2.0

> $ sudo npm install -g jupyter-dashboards-server
> loadIdealTree → cloneCurr ▀ ╢█████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> WARN engine jupyter-dashboards-server@0.8.0: wanted: {"node":"5.10.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
> /usr/local/bin/jupyter-dashboards-server -> /usr/local/lib/node_modules/jupyter-dashboards-server/bin/jupyter-dashboards-server
> 
> > websocket@1.0.24 install /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/websocket
> > (node-gyp rebuild 2> builderror.log) || (exit 0)
> 
> 
> > phosphor-dragdrop@0.9.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/phosphor-dragdrop
> > npm dedupe
> 
> npm ERR! Linux 4.4.0-59-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "dedupe"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! path /usr/local/lib/node_modules/.staging
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall rmdir
> 
> npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/.staging'
> npm ERR!     at Error (native)
> npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/.staging']
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'rmdir',
> npm ERR!   path: '/usr/local/lib/node_modules/.staging' }
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/phosphor-dragdrop/npm-debug.log
> /usr/local/lib
> └── (empty)
> 
> npm ERR! Linux 4.4.0-59-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "jupyter-dashboards-server"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! phosphor-dragdrop@0.9.1 postinstall: `npm dedupe`
> npm ERR! Exit status 243
> npm ERR! 
> npm ERR! Failed at the phosphor-dragdrop@0.9.1 postinstall script 'npm dedupe'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the phosphor-dragdrop package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm dedupe
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs phosphor-dragdrop
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls phosphor-dragdrop
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/<user>/npm-debug.log
> npm ERR! code 1
> 
>

**Comment by galenwilkerson** [comment]
This seemed to work:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by parente** [comment]
Thanks for reporting. If you you have some spare time, would you mind adding this info to the wiki under github.com/jupyter-incubator/dashboards_server? Thanks!

**Comment by galenwilkerson** [comment]
Hi Peter, I was wondering when you think all of this installation and running will stabilize?  It would be great if it was a bit easier to install and use.  I've had to switch to shiny since that seems very robust and functional, but I would prefer python/jupyter.   best

**Comment by parente** [comment]
@galenwilkerson The installation of the dashboard extension has no issues and is stable. If you're talking about jupyter-incubator/dashboards_server project, that's a different story.

I'm currently spending my open source contribution cycles on bringing jupyter/dashboards and jupyter/kernelgateway up to speed to work with the impending release of notebook 5.0. I'm also not super positive on the future of the dashboard_server project (clarifying: not jupyter dashboards in general, just *that* repository) given how far it is lagging behind the jupyterlab version it uses, how the upcoming ipywidgets 6.0 release is likely to be incompatible with it, and the high likelihood that [jupyterlab will desire / require a different design](https://github.com/jupyterlab/jupyterlab/issues/1640).

**Comment by galenwilkerson** [comment]
Thanks Peter, good to know.   I need a standalone web dashboard (no python
code/access), so as far as I understand, need the dashboard server (unless
another option is available).

I spent a lot of time trying to get this to work, so it could be helpful to
make the status more evident to other potential server users.
Good work though, I know this is a lot to do.

best
