### ISSUE TITLE
Is there a Dockerfile example of latest dashboards/dashboards_server/bundlers/gateway?

### ISSUE THREAD

**Issue by rs2** [jupyter/dashboards#295]
Pip installing lots of components downgrades dependencies for other components, so to make things work have to fallback to:

IPYWIDGETS_VER: "5.2.\*"
DASHBOARDS_VER: "0.6.\*"
CMS_VER: "0.6.\*"
BUNDLER_VER: "0.8.\*"

**Comment by parente** [comment]
The dashboards server and bundler projects are woefully behind. I am using what time I do have available for open source to contribute to the top-level jupyter projects, and simply don't have cycles to keep the ones still in incuator abreast of the changes in the ipywidgets and jupyterlab.

If you'd like to submit a PR, https://github.com/jupyter-incubator/dashboards_setup can probably be brought up to date a bit with the latest dashboards server and notebook versions, but ipywidgets will still likely need to be 5.2.
