### ISSUE TITLE
Clarification of "Developer tasks"

### ISSUE THREAD

**Issue by ssackett** [jupyter/dashboards#303]
Refer to:  http://jupyter-dashboards-layout.readthedocs.io/en/latest/development.html

The above page contains instructions to "Create a conda environment with the necessary dev and test dependencies."

These instruction appear to be an abbreviation of the procedure.  Can you explain more fully what needs to be done?

Thanks.

**Comment by parente** [comment]
The `make env` command runs the necessary conda commands to do what the text says. If you want to know what the Makefile is doing under the covers for that step, you can see it here: https://github.com/jupyter/dashboards/blob/master/Makefile#L29

**Comment by ssackett** [comment]
Peter,

The confusion on my part is how to follow the instructions.
The instructions say:
-------------
Create a conda environment with the necessary dev and test dependencies.

cd dashboards
make env
-------------

Where do I find the directory named "dashboards" that contains the "make" file?

Thanks,

Steve

**Comment by ssackett** [comment]
Peter,

I found the problem so please disregard my question.  

Here's what I did wrong:

I cloned the dashboards repository using the --bare switch,  apparently this does not install the Makefile.  Also the directory ends up being called dashboards.git in that case and so my confusion over the location of the "dashboards" directory.

Thanks,

Steve
