### ISSUE TITLE
Demo Notebook "Scotch Dashboard" runtime error

### ISSUE THREAD

**Issue by ssackett** [jupyter/dashboards#304]
I am having a problem running one of the dasboards demo notebooks.  Any help you can give me will be greatly appreciated.

I am running on OSX Sierra, using Safari browser and running the Anaconda distribution.  I have installed the dasboards environment and activated it.  

I have switched to .../dashboards/etc/notebooks and started the notebook server. Next I opened the index notebook and used the link on it to launch "scotch_dashboard".  I then select "Cell|Run All" to execute the notebook.

The notebook fails to execute completely and terminates with the message: 
AttributeError: 'Series' object has no attribute 'order'

Below is the full contents of the cell that shows the error message:

----
picker_w = widgets.interact(on_pick_scotch, Scotch=list(sim_df.index))
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda/envs/dashboards/lib/python3.6/site-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    215                     value = widget.get_interact_value()
    216                     self.kwargs[widget._kwarg] = value
--> 217                 self.result = self.f(**self.kwargs)
    218                 if self.auto_display and self.result is not None:
    219                     display(self.result)

<ipython-input-14-eec22dbf2017> in on_pick_scotch(Scotch)
      2     name = Scotch
      3     # Get top 6 similar whiskeys, and remove this one
----> 4     top_df = get_similar(name, 6).iloc[1:]
      5     # Get bottom 5 similar whiskeys
      6 #     bottom_df = get_similar(name, 5, False)

<ipython-input-13-1ac3aa161119> in get_similar(name, n, top)
      1 def get_similar(name, n, top=True):
----> 2     a = sim_df[name].order(ascending=False)
      3     a.name = 'Similarity'
      4     df = pd.DataFrame(a) #.join(features_df).iloc[start:end]
      5     return df.head(n) if top else df.tail(n)

~/anaconda/envs/dashboards/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   3079             if name in self._info_axis:
   3080                 return self[name]
-> 3081             return object.__getattribute__(self, name)
   3082 
   3083     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'order'

**Comment by parente** [comment]
Thanks for the report. There's another open issue about this and a pull request open that I need to finish up the fix it. In the meantime, switch order to sort_values. The pandas API changed.

**Comment by parente** [comment]
I just merged pr #302 which should fix this issue. Git pull and give it a try.
