### ISSUE TITLE
ImportError: No module named jupyter_dashboards during installation

### ISSUE THREAD

**Issue by bluprince13** [jupyter/dashboards#309]
I've installed dashboards with `pip install jupyter_dashboards`

Then I use the following command:
`jupyter nbextension install --py jupyter_dashboards --sys-prefix`

Only to get this error:
```
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\jupyter-nbextension-script.py", line 10, in <module
>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, i
n launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 65
8, in launch_instance
    app.start()
  File "C:\Anaconda2\lib\site-packages\notebook\nbextensions.py", line 900, in s
tart
    super(NBExtensionApp, self).start()
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 256, i
n start
    self.subapp.start()
  File "C:\Anaconda2\lib\site-packages\notebook\nbextensions.py", line 678, in s
tart
    self.install_extensions()
  File "C:\Anaconda2\lib\site-packages\notebook\nbextensions.py", line 657, in i
nstall_extensions
    **kwargs
  File "C:\Anaconda2\lib\site-packages\notebook\nbextensions.py", line 211, in i
nstall_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Anaconda2\lib\site-packages\notebook\nbextensions.py", line 1034, in
_get_nbextension_metadata
    m = import_item(module)
  File "C:\Anaconda2\lib\site-packages\traitlets\utils\importstring.py", line 42
, in import_item
    return __import__(parts[0])
ImportError: No module named jupyter_dashboards
```

**Comment by parente** [comment]
Can you run `pip list` and share the list of packages you have installed?

**Comment by bluprince13** [comment]
alabaster (0.7.8)
anaconda-client (1.4.0)
anaconda-navigator (1.2.1)
argcomplete (1.0.0)
astropy (1.2.1)
Babel (2.3.3)
backports-abc (0.4)
backports.shutil-get-terminal-si
backports.ssl-match-hostname (3.
beautifulsoup4 (4.4.1)
bitarray (0.8.1)
blaze (0.10.1)
bokeh (0.12.0)
boto (2.40.0)
Bottleneck (1.1.0)
cdecimal (2.3)
cffi (1.6.0)
chest (0.2.3)
click (6.6)
cloudpickle (0.2.1)
clyent (1.2.2)
colorama (0.3.7)
colorlover (0.2.1)
comtypes (1.1.2)
conda (4.3.29)
conda-build (1.21.3)
configobj (5.0.6)
configparser (3.5.0b2)
contextlib2 (0.5.3)
cryptography (1.4)
cufflinks (0.12.0)
cycler (0.10.0)
Cython (0.24)
cytoolz (0.8.0)
dask (0.10.0)
datashape (0.5.2)
decorator (4.0.10)
dill (0.2.5)
Django (1.10.6)
docutils (0.12)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.11.1)
Flask-Cors (2.1.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
gevent (1.1.1)
gitdb2 (2.0.3)
GitPython (2.1.7)
greenlet (0.4.10)
grin (1.2.1)
h5py (2.6.0)
HeapDict (1.0.0)
idna (2.1)
imagesize (0.7.1)
ipaddress (1.0.16)
ipycache (0.1.4)
ipykernel (4.6.1)
ipython (5.4.1)
ipython-genutils (0.1.0)
ipywidgets (7.0.0)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
jupyter-dashboards (0.2.0)
line-profiler (2.0)
llvmlite (0.11.0)
locket (0.2.0)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
menuinst (1.4.1)
mistune (0.7.2)
mpmath (0.19)
multipledispatch (0.4.8)
nb-anacondacloud (1.1.0)
nb-conda (1.1.0)
nb-conda-kernels (1.0.3)
nbconvert (4.2.0)
nbformat (4.4.0)
nbpresent (3.0.2)
nbsphinx (0.2.14)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (5.0.0)
numba (0.26.0)
numexpr (2.6.0)
numpy (1.11.1)
odo (0.5.0)
openpyxl (2.3.2)
pandas (0.18.1)
partd (0.3.4)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.1)
pbr (3.1.1)
pep8 (1.7.0)
pickleshare (0.7.2)
Pillow (3.2.0)
pip (9.0.1)
plotly (2.0.11)
ply (3.8)
prompt-toolkit (1.0.15)
psutil (4.3.0)
py (1.4.31)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.2.3)
Pygments (2.1.3)
pyOpenSSL (16.2.0)
pyparsing (2.1.4)
pyreadline (2.1)
PySide (1.2.4)
pytest (2.9.2)
python-dateutil (2.5.3)
pytz (2016.4)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
qtconsole (4.2.1)
QtPy (1.0.2)
requests (2.14.2)
rope (0.9.4)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.17.1)
setuptools (23.0.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
smmap2 (2.0.3)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
Sphinx (1.6.3)
sphinx-git (10.0.0)
sphinx-rtd-theme (0.1.9)
sphinxcontrib-fulltoc (1.2.0)
sphinxcontrib-websupport (1.0.1)
spyder (2.3.9)
SQLAlchemy (1.0.13)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.8.0)
tornado (4.3)
tqdm (4.15.0)
traitlets (4.3.2)
typing (3.6.2)
unicodecsv (0.14.1)
wcwidth (0.1.7)
Werkzeug (0.11.10)
wheel (0.29.0)
widgetsnbextension (3.0.2)
win-unicode-console (0.5)
xlrd (1.0.0)
XlsxWriter (0.9.2)
xlwings (0.7.2)
xlwt (1.1.2)

**Comment by parente** [comment]
It looks like you have jupyter-dashboards 0.2.0 installed which is quite old. The latest release on pypi is 0.7.0 (https://pypi.org/project/jupyter_dashboards/). Try a `pip install --update jupyter_dashboards`.

**Comment by bluprince13** [comment]
Thank you! That solved the problem - I should have checked the version myself before raising the issue. Sorry!

**Comment by parente** [comment]
No problem. Cheers!
