### ISSUE TITLE
Dashboard view not showing up

### ISSUE THREAD

**Issue by martinapugliese** [jupyter/dashboards#310]
I've installed and enabled the dashboard extension as per [docs](http://jupyter-dashboards-layout.readthedocs.io/en/latest/getting-started.html), an on Python3, as in

```
pip3 install jupyter_dashboards
jupyter dashboards quick-setup --sys-prefix
```

Then launching a notebook does not show the dashboard toolbar:

![screen shot 2017-10-20 at 12 41 54](https://user-images.githubusercontent.com/4414857/31819325-240c34c2-b594-11e7-9f44-3229db36afdf.png)

And this is the server info

![screen shot 2017-10-20 at 12 41 35](https://user-images.githubusercontent.com/4414857/31819348-330980b0-b594-11e7-878b-f113b6edd392.png)

Tried the suggestion at the bottom of the docs page in case it was a legacy issue, but does not seem to apply as I have this in the Jupyter config file

```

## DEPRECATED use the nbserver_extensions dict instead
#c.NotebookApp.server_extensions = []
```

Any help on what's wrong?

**Comment by parente** [comment]
Can you run pip3 list and jupyter nbextension list and post the out here?

**Comment by martinapugliese** [comment]
@parente Sure. 

## pip3 list

`pip3 list` spits

pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appnope (0.1.0)
beautifulsoup4 (4.5.3)
bleach (1.5.0)
bokeh (0.12.9)
botocore (1.7.25)
branca (0.2.0)
certifi (2017.7.27.1)
cffi (1.9.1)
chardet (3.0.4)
cryptography (1.7.2)
cycler (0.10.0)
decorator (4.1.2)
docutils (0.14)
dropbox (8.0.0)
entrypoints (0.2.2)
folium (0.5.0)
future (0.16.0)
giphypop (0.3)
html5lib (0.9999999)
idna (2.5)
inflection (0.3.1)
ipykernel (4.5.2)
ipython (5.2.2)
ipython-genutils (0.2.0)
ipyvolume (0.2.3)
ipywidgets (6.0.0b10)
Jinja2 (2.9.5)
jmespath (0.9.3)
JPype1 (0.6.2)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.1.0)
jupyter-contrib-core (0.3.3)
jupyter-core (4.3.0)
jupyter-dashboards (0.7.0)
jupyter-nbextensions-configurator (0.2.8)
lxml (3.7.3)
MarkupSafe (0.23)
matplotlib (2.0.0)
mistune (0.7.3)
more-itertools (2.5.0)
nbconvert (5.1.1)
nbformat (4.4.0)
ndg-httpsclient (0.4.2)
networkx (1.11)
nltk (3.2.2)
notebook (4.4.1)
numpy (1.13.1)
olefile (0.44)
pandas (0.19.2)
pandocfilters (1.4.1)
patsy (0.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
plotly (2.0.15)
powerlaw (1.4.3)
prompt-toolkit (1.0.13)
psycopg2 (2.7.3)
ptyprocess (0.5.1)
pyasn1 (0.2.3)
PyAthenaJDBC (1.3.0)
pycparser (2.17)
Pygments (2.2.0)
pyOpenSSL (16.2.0)
pyparsing (2.1.10)
python-dateutil (2.6.1)
python-Levenshtein (0.12.0)
pytrends (4.1.1)
pytz (2016.10)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.2)
qtconsole (4.2.1)
Quandl (3.0.1)
requests (2.18.3)
scikit-image (0.13.0)
scikit-learn (0.19.0)
scipy (0.18.1)
seaborn (0.8)
setuptools (36.6.0)
simplegeneric (0.8.1)
six (1.11.0)
sklearn (0.0)
SQLAlchemy (1.1.13)
statsmodels (0.8.0)
terminado (0.6)
testpath (0.3)
tornado (4.5.2)
traitlets (4.3.2)
traittypes (0.0.6)
urllib3 (1.22)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (2.0.0b19)
wikipedia (1.4.0)
xlrd (1.1.0)

## jupyter nbextension list

while `jupyter nbextension` spits

jupyter nbextension list
Known nbextensions:
  config dir: /Users/martina/.jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      jupyter-js-widgets/extension  enabled
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

Take it as the dashboard one is not enabled? If so, why, given the above command from the docs ended fine?

**Comment by martinapugliese** [comment]
@parente  Right, to me looks like the problem is the extension didn't install correctly. A

`pip3 freeze | grep jupyter`

shows it is there:

> jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.3
jupyter-core==4.3.0
jupyter-dashboards==0.7.0

but when running 

`jupyter nbextension install --py jupyter_dashboards --sys-prefix`, which is part of the command for the quick-setup of it, I get a 

> ImportError: No module named jupyter_dashboards

**Comment by martinapugliese** [comment]
To add some more digging, this is because the `jupyter nbextension` is calling a script which is for Python2.7, which I have installed but haven't installed the extension for. Trying to understand how to make it work for the Python3 installation.

**Comment by parente** [comment]
The pip list shows notebook 4.4.1 installed but your screenshot shows 5.0 running. So I’m guessing the extension installled into a different environment against the older notebook server (which it’s not compatible with) but you’re running notebook 5.0 out of a different environment without the extensions installed and activated properly.

**Comment by parente** [comment]
(Can post more help when I’m not on a mobile device.)

**Comment by martinapugliese** [comment]
@parente you're totally right, checked the served is the older one. The extension wasn't installed in fact. Closing this as now resolved, thanks very much for pointing to right direction.

**Comment by kurt-rhee** [comment]
Hello I believe I am having a similar issue 

# packages in environment at C:\Users\simon.rhee\AppData\Local\Continuum\anaconda3\envs\jup_env:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                   py36_1    anaconda
backcall                  0.1.0                    py36_0    anaconda
bleach                    3.1.0                    py36_0    anaconda
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
colorama                  0.4.1                    py36_0    anaconda
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                    py36_1    anaconda
defusedxml                0.6.0                      py_0    anaconda
entrypoints               0.3                      py36_0    anaconda
freetype                  2.10.0               h5db478b_0    conda-forge
icu                       58.2                 ha66f8fd_1    anaconda
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py36h39e3cac_0    anaconda
ipython                   7.5.0            py36h39e3cac_0    anaconda
ipython_genutils          0.2.0            py36h3c5d0ee_0    anaconda
ipywidgets                7.4.2                    py36_0    anaconda
jedi                      0.13.3                   py36_0    anaconda
jinja2                    2.10.1                   py36_0    anaconda
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.1                    py36_0    anaconda
jupyter                   1.0.0                    py36_7    anaconda
jupyter_client            5.2.4                    py36_0    anaconda
jupyter_console           6.0.0                    py36_0    anaconda
jupyter_core              4.4.0                    py36_0    anaconda
jupyter_dashboards        0.7.0                 py36_1000    conda-forge
kiwisolver                1.1.0            py36he980bc4_0    conda-forge
lesscpy                   0.13.0                     py_1    conda-forge
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0    anaconda
libsodium                 1.0.16               h9d3ae62_0    anaconda
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36he774522_0    anaconda
matplotlib                3.1.0                    py36_1    conda-forge
matplotlib-base           3.1.0            py36h2852a4a_1    conda-forge
mistune                   0.8.4            py36he774522_0    anaconda
mkl                       2019.4                      245
msys2-conda-epoch         20160418                      1
nbconvert                 5.5.0                      py_0    anaconda
nbformat                  4.4.0            py36h3a5bc1b_0    anaconda
notebook                  5.7.8                    py36_0    anaconda
numpy                     1.16.4           py36hc71023c_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pandas                    0.24.2           py36he350917_0    conda-forge
pandoc                    2.2.3.2                       0    anaconda
pandocfilters             1.4.2                    py36_1    anaconda
parso                     0.4.0                      py_0    anaconda
pickleshare               0.7.5                    py36_0    anaconda
pip                       19.1.1                   py36_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.6.0                    py36_0    anaconda
prompt_toolkit            2.0.9                    py36_0    anaconda
pygments                  2.4.2                      py_0    anaconda
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py36ha878b3d_0    anaconda
pyrsistent                0.14.11          py36he774522_0    anaconda
python                    3.6.7             he025d50_1004    conda-forge
python-dateutil           2.8.0                    py36_0    anaconda
pytz                      2019.1                     py_0    conda-forge
pywinpty                  0.5.5                 py36_1000    anaconda
pyzmq                     18.0.0           py36ha925a31_0    anaconda
qt                        5.9.7                hc6833c9_1    conda-forge
qtconsole                 4.5.1                      py_0    anaconda
send2trash                1.5.0                    py36_0    anaconda
setuptools                41.0.1                   py36_0    conda-forge
sip                       4.19.13          py36ha925a31_0    anaconda
six                       1.12.0                   py36_0    anaconda
sqlite                    3.28.0               he774522_0    anaconda
terminado                 0.8.2                    py36_0    anaconda
testpath                  0.4.2                    py36_0    anaconda
tornado                   6.0.2            py36he774522_0    anaconda
traitlets                 4.3.2            py36h096827d_0    anaconda
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7            py36h3d5aa90_0    anaconda
webencodings              0.5.1                    py36_1    anaconda
wheel                     0.33.4                   py36_0    conda-forge
widgetsnbextension        3.4.2                    py36_0    anaconda
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    anaconda
xlrd                      1.2.0                      py_0    conda-forge
zeromq                    4.3.1                h33f27b4_3    anaconda
zlib                      1.2.11               h62dcd97_3    anaconda

Known nbextensions:
  config dir: C:\Users\simon.rhee\AppData\Local\Continuum\anaconda3\envs\jup_env\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      jupyter_dashboards/notebook/main enabled
      - Validating: ok
