### ISSUE TITLE
Temporary notebook server for demos linked from wiki page is no longer active and now redirects to a site serving {ad,scam,mal}ware

### ISSUE THREAD

**Issue by kh90909** [jupyter/dashboards#311]
The link in question is to ```jupyter.cloudet.xyz``` and it's found at the bottom of the main wiki page: https://github.com/jupyter/dashboards/wiki

My adblocker (Adblock Plus) blocks the offending content, but this link should be removed to protect unsuspecting users.

**Comment by parente** [comment]
Thanks for the report. I've removed the out-of-date page and link.
