### ISSUE TITLE
Make Meetup Outreach demo more parallelizable (remove use of globals)

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter/dashboards#39]
The Meetup Outreach demo (see issue #30) makes extensive use of globals in the Python code. While this works well when running the demo locally, it doesn't allow us to make good use of distributed nodes.

We need to replace the use of globals through the use of map/reduce and broadcast vars & accumulators.

**Comment by parente** [comment]
Closing as won't fix a year and a half later.
